bohdan_moshchenko_blog_homepage:
    path:     /
    defaults: { _controller: BohdanMoshchenkoBlogBundle:Default:index }

bohdan_moshchenko_blog_post:
    path:     /post
    defaults: { _controller: BohdanMoshchenkoBlogBundle:Default:post }
